Docker.DotNet/Models/ListContainersParameters.cs

Cause System.InvalidOperationException: Cannot convert type System.Int64 using Docker.DotNet.Models.BoolQueryStringConverter.

Remove BoolQueryStringConverter from ListContainersParameters.Limit.

---

Docker.DotNet/Models/Config.cs
Docker.DotNet/Models/HostConfig.cs
Docker.DotNet/Models/SystemInfoResponse.cs
Docker.DotNet/Properties/AssemblyInfo.cs
NuGet/Docker.DotNet.1.1.2.nuspec

Adding dependency to NuSpec file as per issue https://github.com/ahmetalpbalkan/Docker.DotNet/issues/18.  NuGet package will need to be rebuilt and deployed in order for changes to take effect.

Adding new NuSpec file with Microsoft.Bcl.Async dependency.

---

.gitignore

properly ignores the packages folder.

ignore nuget packages folder all together

---

Docker.DotNet.BasicAuth/BasicAuthCredentials.cs
Docker.DotNet.X509/CertificateCredentials.cs
Docker.DotNet/AnonymousCredentials.cs
Docker.DotNet/Credentials.cs
Docker.DotNet/DockerClient.cs
Docker.DotNet/DockerClientConfiguration.cs
Docker.DotNet/IDockerClient.cs

The current implementation of `DockerClient` does two things wrong:
- It creates an `HttpClient` instance each time you make a request. This will result in creating inner handlers in each request which does the connection pooling. 
- It leaves `HttpClient` instances undisposed which will result in open TCP connections as inner handlers don't close them for certain period of time by default.
The best usage of `HttpClient` is to create one instance of this and use it for the entire app lifetime as its members are thread safe + its inner handler does connection pooling. See [here](http://stackoverflow.com/questions/15705092/do-httpclient-and-httpclienthandler-have-to-be-disposed) for more info.
However, as you have special cases for credentials, I started disposing `HttpClient` but left the …

made DockerClient to use only one handler per instance

---

Docker.DotNet.BasicAuth/BasicAuthCredentials.cs
Docker.DotNet.BasicAuth/BasicAuthHandler.cs
Docker.DotNet.BasicAuth/Docker.DotNet.BasicAuth.csproj
Docker.DotNet.X509/CertificateCredentials.cs
Docker.DotNet/AnonymousCredentials.cs
Docker.DotNet/ContainerOperations.cs
Docker.DotNet/Credentials.cs
Docker.DotNet/DockerClient.cs
Docker.DotNet/DockerClientConfiguration.cs
Docker.DotNet/ImageOperations.cs
Docker.DotNet/MiscellaneousOperations.cs

When calling methods that return a stream, the stream cannot be read from due to HttpClient being disposed, which results in any requests still in flight being disposed of.
I've done some refactoring so that HttpClient has only one instance and then the credential instances inject a httpmessagehandler rather than being responsible for creating the HttpClient.
Because I've had to make it a single instance I've had to make changes to the way timeouts work, so instead of setting the timeout value on HttpClient I configure the cancellation token to timeout which behaviour wise is the same.
I've also added configure await on awaited calls just as it's considered good practice.

Fix for defect where streams are being closed prematurely

---

Docker.DotNet/ContainerOperations.cs
Docker.DotNet/Docker.DotNet.csproj
Docker.DotNet/DockerApiStreamedResponse.cs
Docker.DotNet/DockerClient.cs
Docker.DotNet/IContainerOperations.cs
Docker.DotNet/Models/ContainerPathStat.cs
Docker.DotNet/Models/ContainerPathStats.cs
Docker.DotNet/Models/ExtractArchiveToContainerParameters.cs
Docker.DotNet/Models/GetArchiveFromContainerParameters.cs
Docker.DotNet/Models/GetArchiveFromContainerResponse.cs
Docker.DotNet/Models/HostConfig.cs

This is to introduce api changes introduced in 1.20.
* `GET /containers/(id)/archive` get an archive of filesystem content from a container.
* `PUT /containers/(id)/archive` upload an archive of content to be extracted to an existing directory inside a container’s filesystem.
* `POST /containers/(id)/copy` is deprecated in favor of the above `archive` endpoint which can be used to download files and directories from a container.
* The `hostConfig` option now accepts the field `GroupAdd`, which specifies a list of additional groups that the container process will run as.
Most of it is pretty similar to existing methods, I had to add an extra method to dockerclient so I could retrieve the stream along with its headers. One thing I wasn't quote sure about was whether the HEAD request to the …

Added features introduced in api version 1.20

---

Docker.DotNet/Endpoints/NetworkOperations.cs

@ahmetalpbalkan @jterry75 
The networks URI for list and inpsect incorrectly included "/json" at the end, removing them fixes the problem.
Signed-off-by: Stefan J. Wernli <swernli@microsoft.com>

Fixing network URI bug.

---

Docker.DotNet.BasicAuth/project.json
Docker.DotNet/project.json

@jterry75 @ahmetalpbalkan @jstarks 
We've hit an issue compiling for netstandard1.3 using the latest version of the dotnet CLI (reported here: https://github.com/dotnet/cli/issues/2739). The current mechanism used to incorrectly report success during compile, but required runtime references couldn't be found with the latest dotnet CLI.  Until we have a resolution to the issue or better guidance on how to compile for DNXCore, it's safer in the short term to remove that build target.

Temporarily removing support for netstandard1.3

---

Docker.DotNet/Models/Address.Generated.cs
Docker.DotNet/Models/ContainerInspectResponse.Generated.cs
Docker.DotNet/Models/ContainerJSONBase.Generated.cs
Docker.DotNet/Models/ContainerNode.Generated.cs
Docker.DotNet/Models/ContainerState.Generated.cs
Docker.DotNet/Models/ContainerWaitResponse.Generated.cs
Docker.DotNet/Models/ContainersListParameters.Generated.cs
Docker.DotNet/Models/DefaultNetworkSettings.Generated.cs
Docker.DotNet/Models/EndpointSettings.Generated.cs
Docker.DotNet/Models/HostConfig.Generated.cs
Docker.DotNet/Models/ImageSearchResponse.Generated.cs
Docker.DotNet/Models/NetworkSettings.Generated.cs
Docker.DotNet/Models/NetworkSettingsBase.Generated.cs
Docker.DotNet/Models/PidsStats.Generated.cs
Docker.DotNet/Models/Port.Generated.cs
Docker.DotNet/Models/RestartPolicy.Generated.cs
Docker.DotNet/Models/SystemInfoResponse.Generated.cs

1. Fixes a bug where in Go int and uint are converted to the runtime type
size not the standard 32bit like in C#. This updates the generator to
output int and uint as long and ulong instead so we dont get type
mismatches from the service.

Resolves: #59

---

Docker.DotNet/JsonSerializer.cs

Resolves an issue where the Docker daemon might not send an actual value
that can be deserialized into the strongly typed C# model. In go values
like this are given the default value of the type itself but it does not
cause a failure in deserialization.
Resolves: #61

Handle deserializing null values to defaults in C#

---

Docker.DotNet.BasicAuth/BasicAuthCredentials.cs
Docker.DotNet.BasicAuth/MaybeSecureString.cs
Docker.DotNet.BasicAuth/project.json
Docker.DotNet.X509/CertificateCredentials.cs
Docker.DotNet.X509/project.json
Docker.DotNet/DockerClient.cs
Docker.DotNet/EnumerableQueryStringConverter.cs
Docker.DotNet/MapQueryStringConverter.cs
Docker.DotNet/Microsoft.Net.Http.Client/ManagedHandler.cs
Docker.DotNet/QueryStringParameterAttribute.cs
Docker.DotNet/project.json
NuGet.Config

Makes the changes required in order to release Docker.DotNet for
UAP10,NetCoreApp, and NetStandard.
Resolves: #56

Fixes .NET Core,uap10,netstandard builds.

---

Docker.DotNet/DockerClient.cs
Docker.DotNet/DockerPipeStream.cs
Docker.DotNet/Endpoints/ContainerOperations.cs
Docker.DotNet/Endpoints/IContainerOperations.cs
Docker.DotNet/Microsoft.Net.Http.Client/BufferedReadStream.cs
Docker.DotNet/Microsoft.Net.Http.Client/HttpConnectionResponseContent.cs
Docker.DotNet/Microsoft.Net.Http.Client/ManagedHandler.cs
Docker.DotNet/Microsoft.Net.Http.Client/WriteClosableStream.cs
Docker.DotNet/MultiplexedStream.cs
Docker.DotNet/QueryStringParameterAttribute.cs
Docker.DotNet/project.json

The key tricky part here is that we have to have a way to shut down the write path to notify Docker that stdin has closed. This is done with Socket.Shutdown() for sockets (TCP), and a zero-byte write for named pipe.

Support attaching to Docker container input/output

---

Docker.DotNet/Microsoft.Net.Http.Client/ManagedHandler.cs

When running on DotNet Core on Linux, the ```System.PlatformNotSupported``` was firing when checking for proxy bypass. I could not see any way to set ```UseProxy``` to false from client code, and so propose that this exception is handled to enable functionality on platforms that don't support a proxy.
If a proxy is in fact required on a platform that doesn't support it, I expect the call to ```Proxy.GetProxy()``` to still fail as expected.

Handle System.PlatformNotSupported exception when checking to see if a proxy can be used.

---

Docker.DotNet.BasicAuth/Docker.DotNet.BasicAuth.xproj
Docker.DotNet.X509/Docker.DotNet.X509.xproj
Docker.DotNet/Docker.DotNet.xproj
Docker.DotNet/Microsoft.Net.Http.Client/BufferedReadStream.cs
Docker.DotNet/Microsoft.Net.Http.Client/ChunkedWriteStream.cs
Docker.DotNet/Microsoft.Net.Http.Client/HttpConnectionResponseContent.cs
Docker.DotNet/MultiplexedStream.cs
Docker.DotNet/project.json
global.json

Hi! I looked into the code for this project and noticed there were a few places where performance could be improved. I'll try to break down the changes I made here:
- Cache the bytes written in `ChunkedWriteStream.EndContentAsync`
- Use a pooled array from `System.Buffers.ArrayPool` in `BufferedReadStream` (I added `System.Buffers` as a dependency)
- Call `base.Dispose` in `HttpConnectionResponseContent` (since `HttpContent.Dispose` actually does work)
I also made a few other changes with the tooling, to make it easier to build/setup the project:
- Convert the DNX `.xproj` files to use the CLI
- Update the `global.json` to use the RTM .NET Core SDK (`preview1` is RC2, `preview2` is RTM)

Reduce memory consumption in Microsoft.Net.Http.Client, update tooling

---

appveyor.yml

This just ensures that there are no build breaks. It doesn't do any testing.

Add basic appveyor manifest

---

Docker.DotNet/Models/ContainerListResponse.Generated.cs
tools/specgen/specgen.go

Resolves: #92
Fixes a bug where container.Created was a long unix date time and converts
that to a C# System.DateTime object.

Returns container created time as DateTime

---

Docker.DotNet/Endpoints/ContainerOperations.cs
Docker.DotNet/Endpoints/IContainerOperations.cs
Docker.DotNet/Models/ContainerExecCreateParameters.Generated.cs
Docker.DotNet/Models/ExecConfig.Generated.cs
tools/specgen/modeldefs.go
tools/specgen/specgen.go

@jterry75 @jstarks 
Promoting ExecConfig to a full generated object, where ContainerExecCreateParameters and ContainerExecStartParameters both have copy constructors from ExecConfig.  This will make it easier for callers who want to call both, and also allows for exec starts to pass the correct full set of params needed to perform an attach.

Fixing the exec start parameters to be the full ExecConfig.

---

Docker.DotNet/Endpoints/IMiscellaneousOperations.cs
Docker.DotNet/Endpoints/MiscellaneousOperations.cs
Docker.DotNet/Models/ImageLoadParameters.Generated.cs
Docker.DotNet/QueryString.cs
tools/specgen/modeldefs.go

@jterry75 @jstarks 
This change expands on the MiscellaneousOperations methods for loading and saving images, and updates the ImageLoadParameters.Quiet to be required since DockerD defaults to true.

Updating image save/load methods.

---

Docker.DotNet.BasicAuth/BasicAuthCredentials.cs
Docker.DotNet.BasicAuth/MaybeSecureString.cs
Docker.DotNet.BasicAuth/project.json
Docker.DotNet.X509/CertificateCredentials.cs
Docker.DotNet.X509/project.json
Docker.DotNet/DockerClient.cs
Docker.DotNet/Microsoft.Net.Http.Client/LICENSE-MIT.txt
Docker.DotNet/Microsoft.Net.Http.Client/ManagedHandler.cs
Docker.DotNet/Microsoft.Net.Http.Client/UnixDomainSocketEndPoint.cs
Docker.DotNet/QueryStringParameterAttribute.cs
Docker.DotNet/project.json
appveyor.yml

@jterry75 @jstarks 
These changes prepare the build to work against netstandard1.6, including formatting updates for project.json.
They also introduce unix socket support for connections when running directly on Linux.

Adding unix sockets and building for netstandard1.6

---

Docker.DotNet.X509/CertificateCredentials.cs
Docker.DotNet/BinaryRequestContent.cs
Docker.DotNet/BoolQueryStringConverter.cs
Docker.DotNet/DockerApiException.cs
Docker.DotNet/DockerClient.cs
Docker.DotNet/DockerPipeStream.cs
Docker.DotNet/Endpoints/ContainerOperations.cs
Docker.DotNet/Endpoints/ImageOperations.cs
Docker.DotNet/Endpoints/MiscellaneousOperations.cs
Docker.DotNet/Endpoints/NetworkOperations.cs
Docker.DotNet/HttpUtility.cs
Docker.DotNet/JsonIso8601AndUnixEpochDateConverter.cs
Docker.DotNet/JsonRequestContent.cs
Docker.DotNet/JsonVersionConverter.cs
Docker.DotNet/MultiplexedStream.cs
Docker.DotNet/QueryString.cs
Docker.DotNet/QueryStringConverterInstanceFactory.cs
Docker.DotNet/QueryStringParameterAttribute.cs

Refactors a few patterns of code design.
Removes redundant assignments.
Replaces string.Format with string interpolation.
Uses var or strong declaration.
Inline's path strings to avoid temporary assignment.

Minor code cleanup.

---

Docker.DotNet/Models/Annotations.Generated.cs
Docker.DotNet/Models/CAConfig.Generated.cs
Docker.DotNet/Models/ClusterInfo.Generated.cs
Docker.DotNet/Models/ContainerAttachParameters.Generated.cs
Docker.DotNet/Models/DispatcherConfig.Generated.cs
Docker.DotNet/Models/Driver.Generated.cs
Docker.DotNet/Models/ExternalCA.Generated.cs
Docker.DotNet/Models/Info.Generated.cs
Docker.DotNet/Models/Meta.Generated.cs
Docker.DotNet/Models/OrchestrationConfig.Generated.cs
Docker.DotNet/Models/RaftConfig.Generated.cs
Docker.DotNet/Models/Spec.Generated.cs
Docker.DotNet/Models/SystemInfoResponse.Generated.cs
Docker.DotNet/Models/TaskDefaults.Generated.cs
Docker.DotNet/Models/Version.Generated.cs
tools/specgen/Godeps/Godeps.json
tools/specgen/modeldefs.go
tools/specgen/vendor/github.com/docker/engine-api/types/configs.go
tools/specgen/vendor/github.com/docker/engine-api/types/swarm/node.go
tools/specgen/vendor/github.com/docker/engine-api/types/swarm/service.go
tools/specgen/vendor/github.com/docker/engine-api/types/swarm/swarm.go
tools/specgen/vendor/github.com/docker/engine-api/types/types.go

Resolves: #128 - Adds the 'Logs' parameter to ContainerAttachParameters as
the docker cli didnt use this property even though the daemon supported
it.
Partially implements: #119 - Adds the swarm/services and node models but
doesnt add any endpoint behavior.

Updates Models to release v1.12.0

---

README.md

Looks like Docker changed their url for their api documentation, so I updated the link. The `v1.14` link also wasn't in use, so I dropped it as well.

Updated Docker documentation links

---

Docker.DotNet/Models/Config.Generated.cs
Docker.DotNet/Models/ContainerInspectResponse.Generated.cs
Docker.DotNet/Models/ContainerJSONBase.Generated.cs
Docker.DotNet/Models/ContainerUpdateParameters.Generated.cs
Docker.DotNet/Models/CreateContainerParameters.Generated.cs
Docker.DotNet/Models/HostConfig.Generated.cs
Docker.DotNet/Models/Resources.Generated.cs
Docker.DotNet/Models/UpdateConfig.Generated.cs
tools/specgen/specgen.go

Resolves: #140. When a `*primitive` in Go converts to C# the only possible
conversion is to call this a `primitive?` to maintain the nullablility.

Fixes an issue with nullable primitive types.

---

Docker.DotNet/Models/Config.Generated.cs
Docker.DotNet/Models/CreateContainerParameters.Generated.cs
tools/specgen/specgen.go

Resolves: #139 in that docker handles Config.Volumes very specifically.
Rather than being a map of string struct it actually only uses the keys
which serializes as a flat list of string.

Fixes map[string]struct{} as dictionary

---

src/Docker.DotNet/Models/Actor.Generated.cs
src/Docker.DotNet/Models/EventsMessage.Generated.cs
tools/specgen/specgen.go
tools/specgen/update-generated-code.cmd

For the v1.12.0 release the return type of /events was the
events.Message type in go. This adds that type to the reflection api's
to generate it for the return streams.

Implement /events return type.

---

src/Docker.DotNet/Endpoints/NetworkOperations.cs

ConnectNetworkAsync and DisconnectNetworkAsync were making GET request (+ body) when POST is expected. This resulted in 404 response with the error 
> network {network-id}/connect not found
Code has been updated to use POST

Fix HttpMethod bug in Connect/DisconnectNetworkAsync

---

src/Docker.DotNet/Models/ContainerStatsParameters.Generated.cs
tools/specgen/csharptype.go
tools/specgen/modeldefs.go
tools/specgen/resttag.go
tools/specgen/specgen.go

Resolves: #187
In the docker daemon this property is actually default valued to true not
false so we need to overwrite the default if not assigned.

Fixes an issue with GetContainerStatsAsync hang

---

README.md

Took me a long time to figure out how to connect to the local daemon without exposing it on port 2375 (should have started with the code).
This should really be documented as it is a common use case.

Added example of named pipes URI to connect to local Docker for Windows

---

src/Docker.DotNet/Endpoints/ISwarmOperations.cs
src/Docker.DotNet/Endpoints/SwarmOperations.cs
src/Docker.DotNet/Models/EngineDescription.Generated.cs
src/Docker.DotNet/Models/JoinTokens.Generated.cs
src/Docker.DotNet/Models/ManagerStatus.Generated.cs
src/Docker.DotNet/Models/NodeDescription.Generated.cs
src/Docker.DotNet/Models/NodeListResponse.Generated.cs
src/Docker.DotNet/Models/NodeSpec.Generated.cs
src/Docker.DotNet/Models/NodeStatus.Generated.cs
src/Docker.DotNet/Models/NodeUpdateParameters.Generated.cs
src/Docker.DotNet/Models/Platform.Generated.cs
src/Docker.DotNet/Models/PluginDescription.Generated.cs
src/Docker.DotNet/Models/SwarmInspectResponse.Generated.cs
tools/specgen/modeldefs.go
tools/specgen/specgen.go

This change updates the swarm inspect type to match the type returned by docker (swarm.Swarm) and
adds the types for /nodes/ endpoint operations.

Fixing swarm inspect type and adding Nodes types

---

src/Docker.DotNet/Endpoints/ContainerOperations.cs

The calls to container [wait, stop, restart] were using a timeout of -1 ticks, which causes an immediate cancellation request on the linked token. 
The infinite tmeout static is defined as -1 ms
```c#
private static readonly TimeSpan s_InfiniteTimeout = TimeSpan.FromMilliseconds(Timeout.Infinite);
```
Changed the calls in ContainerOperations to use 
```c#
TimeSpan.FromMilliseconds(Timeout.Infinite)
```

Fixed timeout for a couple of container operations

---

README.md

I'm new to DockerDotNet but I guess ContainerResponse is an old class

ContainerListResponse should be used instead of ContainerResponse

---

src/Docker.DotNet/DockerClient.cs
src/Docker.DotNet/Microsoft.Net.Http.Client/ManagedHandler.cs

This PR fixed problem described in #233 ,
The reason of this problem:
First, create a docket client will create a ManageHandler with no ctor arguments:
https://github.com/Microsoft/Docker.DotNet/blob/9a740b51305180dcc87e0e9bc976e185a8e4e8ac/src/Docker.DotNet/DockerClient.cs#L108
Then, ManageHandler will use TCPSocketOpenerAsync by default:
https://github.com/Microsoft/Docker.DotNet/blob/master/src/Docker.DotNet/Microsoft.Net.Http.Client/ManagedHandler.cs#L23
TCPSocketOpenerAsync will open a new Socket for every request, but ProcessRequestAsync wont Dispose them
https://github.com/Microsoft/Docker.DotNet/blob/master/src/Docker.DotNet/Microsoft.Net.Http.Client/ManagedHandler.cs#L188
I already test this fix with my local environment and confirm it can prevent socket resource leak.
Maybe you …

fix #233 , close socket after SendAsync

---

appveyor.yml

@galvesribeiro - This will be the final commit before the new release v3.125.0. Then I will submit the registry code as a rev as its completed but this brings the core library to everyone with all the recent fixes.

Reving the final appveyor release build.

---

src/Docker.DotNet/Models/Config.Generated.cs
src/Docker.DotNet/Models/CreateContainerParameters.Generated.cs
src/Docker.DotNet/Models/HealthConfig.Generated.cs
src/Docker.DotNet/Models/JSONMessage.Generated.cs
src/Docker.DotNet/Models/ObjectExtensionData.cs
tools/specgen/csharptype.go
tools/specgen/specgen.go

Aux is a []byte slice in go but it is actually a json object for extension data. This fixes the Aux object to allow the user to dynamically check for values rather than fixing the type.
Resolves: #252 
@Sumo-MBryant - Want to give this a shot and see if it works as expected?

Fixes an issue with JSONMessage where Aux is filled out.

---

src/Docker.DotNet/Endpoints/ContainerOperations.cs
src/Docker.DotNet/Endpoints/IContainerOperations.cs

Adds the NoSuchContainerHandler to GetConatinerStatsAsync that was missing.
Reorders the ContainerOperations and IContainerOperations to match the API spec.
Adds the appropriate HTTP URI to the documents for each function.
Resolves: #258

Fixes an issue in GetContainerStatsAsync

---

appveyor.yml

Update to the install script locations to the version hosted on the dotnet website rather than github master.
See https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script
Signed-off-by: Darren Stahl <darst@microsoft.com>
cc @jterry75

Update appveyor install script to download from a stable location

---

src/Docker.DotNet.X509/RSAUtil.cs

RASUtil.GetCertFromPEMFiles fails with an IndexOutOfBoundsException when pem file contains carriage returns.
Carriage Returns working perfectly fine in DockerTLS.
By the way. The readme.md suggest to use openssl to convert the pem files to PRX instead of using RASUtil.GetCertFromPEMFiles which is more practical.

RASUtil.GetCertFromPEMFiles fails with an IndexOutOfBoundsException

---

src/Docker.DotNet/Microsoft.Net.Http.Client/ManagedHandler.cs

In cases where the Proxy is set to null, current code leads to an exception, which bubbles up to the caller. By adding a fix to check the null, we will return ProxyMode.None in such cases.

Fix to handle null web proxy settings.

---

src/Docker.DotNet/Endpoints/ContainerOperations.cs
src/Docker.DotNet/Endpoints/IContainerOperations.cs

Changes the response type from the stream to a ContainerStatsResponse and not JSONMessage like most of the progress API's use.
Resolves: #271

Fixes an issue with GetContainerStatsAsync

---

src/Docker.DotNet/DockerApiException.cs
src/Docker.DotNet/DockerClient.cs

This PR modifies the "make exception from error response" code to always read the response body in case of errors, as there is valuable information in there. When there is no error, the response body is not touched, as before.
Before this PR:
```
Docker API responded with status code=InternalServerError, response=
```
That error says nothing useful.
After this PR:
```
Docker API responded with status code=InternalServerError, response={"message":"Get https://registry.xx.com/v2/xx/xx-xx/manifests/cb: unauthorized: authentication required"}
```
Much better.

Always report error response body

---

src/Docker.DotNet/Microsoft.Net.Http.Client/ManagedHandler.cs

1. Fixes a bug where we were not properly forwarding the AddressFamily of the underlying address
when creating the socket in ManagedHandler.cs
Resolves: #311

Forwards the AddressFamily on Socket Creation

---

src/Docker.DotNet/Models/ImageDeleteParameters.Generated.cs
tools/specgen/modeldefs.go

Since PruneChildren = true actually means no prune children in the code when sending request to Docker daemon and this parameter is called "--no-prune" in Docker API, so Let us give it a better name here.

Give ImageDeleteParameters-PruneChildren a better name

---

README.md
src/Docker.DotNet/Docker.DotNet.csproj
src/Docker.DotNet/DockerClientConfiguration.cs
test/Docker.DotNet.Tests/ISystemOperations.Tests.cs
test/Docker.DotNet.Tests/SupportedOSPlatformsFactAttribute.cs

* Added a new DockerClientConfiguration constructor that automatically detect the current platform and chooses the local docker endpoint Uri using `npipe://./pipe/docker_engine` on Windows and `unix:/var/run/docker.sock` otherwise.
* Updated documentation to reflect that new feature
* Updated the tests to use this new constructor. The tests can now run on Linux, macOS and Windows.

Automatic detection of Windows / Unix

---

README.md

The README lists missing attach to containers as a known issue. It works though, the README is deprecated.

README update: attaching to containers work, remove from listed known issues

---

src/Docker.DotNet/DockerClient.cs
src/Docker.DotNet/DockerClientConfiguration.cs

The timeout for calling Connect on the NamedPipeClientStream used to communicate with the dockerd instance was hardcoded to 100 milliseconds. Made it so it can be configured in DockerClientConfiguration.
Also set the PipeOptions in the NamedPipeClientStream constructor to Asynchronous

Set NamedPipeClientSteam PipeOptions to asynchronous and make timeout configurable

---

src/Docker.DotNet/DockerClient.cs
src/Docker.DotNet/Endpoints/ExecOperations.cs

Do you have any reason not to make ExecOperations available through DockerClient?
Thanks!

Make ExecOperations available

---

README.md

In Docker for Windows (2.0) the default docker engine path is changed. The usage example should be adapted accordingly.

Documentation fix following #368

---

src/Docker.DotNet/Endpoints/ContainerOperations.cs
src/Docker.DotNet/Endpoints/IContainerOperations.cs
src/Docker.DotNet/MultiplexedStream.cs

This is a pull request that fixes #359 
It creates a new overload of  `IContainerOperations.GetContainerLogsAsync` that returns a `MultiplexedStream`, allowing for the logs to be multiplexed for containers without a TTY.
Unlike what the documentation said, I was unable to hijack the connection when `follow` was set,
it would always fail with a "Chunked or Content-Length streams cannot be hijacked" error.
However, I've tested it with all possible combinations of TTY on/off and Follow on/off, and it seems to work fine on all cases even without hijacking the connection.

Fix junk characters in GetContainerLogs

---

src/Docker.DotNet/DockerClient.cs
src/Docker.DotNet/Microsoft.Net.Http.Client/ManagedHandler.cs

It looks like #299 fixed #285 by inventing one point eleven. Works fine from a "not using HTTP/2" perspective, but in my weird use-case of Kestrel proxying a docker endpoint:
````
dbug: Microsoft.AspNetCore.Server.Kestrel[17]
Connection id "0HLT1H1C8TPI1" bad request data: "Unrecognized HTTP version: 'HTTP/1.11'"
`````
`HttpVersion.Version11` not available on all targets.

Fix HTTP version to 1.1

---

src/Docker.DotNet/Endpoints/IContainerOperations.cs
src/Docker.DotNet/Endpoints/IImageOperations.cs

Updated the method header documentation to be more relevant to a .NET consumer, rather than being in terms of the underlying Docker Engine API calls. This covers IContainerOperations and IImageOperations.
If this is acceptable I'll plan to document more.

Documented container and image operation methods.

---

src/Docker.DotNet/Endpoints/ContainerOperations.cs
test/Docker.DotNet.Tests/IContainerOperationsTests.cs

`ContainerOperations.CreateContainerAsync` now throws `DockerImageNotFoundException` instead of `DockerContainerNotFoundException` when the image can't be found.

CreateContainerAsync: Throw DockerImageNotFoundException when image not found

---

src/Docker.DotNet/DockerClient.cs
src/Docker.DotNet/Microsoft.Net.Http.Client/ChunkedReadStream.cs

@galvesribeiro This pull request contains the changes to support the chunked transfer encoding and closes #566 and #554.

fix(#554): Support chunked transfer encoding (HTTP 1.1)

---

src/Docker.DotNet/DockerClient.cs
src/Docker.DotNet/Models/ImageBuildParameters.Generated.cs
test/Docker.DotNet.Tests/IContainerOperationsTests.cs
tools/specgen/modeldefs.go

@galvesribeiro The first commit disposes the `HttpClient`. Usually, you would like to keep a single instance of the `HttpClient` for the entire application. I am not certain if that works with the current implementation. That's why I kept it as a non static field, disposing it makes sense then.
The second one removes the extra properties. I double-checked them against the API docs. `pull` and `outputs` where part of e43cdd96ef089ec20f99defb5b83b047e2bdec04 and detected by my script (as I said, I didn't really check the other way around).
Closes #518, closes  #522.

Fix #518, #522

---

src/Docker.DotNet/DockerClient.cs
test/Docker.DotNet.Tests/IImageOperationsTests.cs
test/Docker.DotNet.Tests/ISystemOperations.Tests.cs

`MakeRequestForRawResponseAsync` is used when calling `IImageOperations.CreateImageAsync`. But the response error from daemon was not handled. Add the error handling before return the result.
Fix issue #555

Handle Reponse Error when building image

---

src/Docker.DotNet/Microsoft.Net.Http.Client/ContentLengthReadStream.cs

The pull request addresses an issue where `Docker.DotNet` throws a `SocketException` when attempting to read from a stream that has an initial content length of 0 bytes.
The Podman container runtime produces a slightly different HTTP response for the HTTP PUT API `/containers/{id}/archive`, where it sets the `Content-Length` field to 0.
**Docker**
```
< HTTP/1.1 200 OK
< Api-Version: 1.41
< Date: Wed, 26 Apr 2023 18:04:19 GMT
< Docker-Experimental: false
< Ostype: linux
< Server: Docker/20.10.23 (linux)
< Transfer-Encoding: chunked
<
```
**Podman**
```
< HTTP/1.1 200 OK
< Api-Version: 1.41
< Libpod-Api-Version: 4.5.0
< Server: Libpod/4.5.0 (linux)
< X-Reference-Id: 0x400067c368
< Date: Wed, 26 Apr 2023 18:27:51 GMT
< Content-Length: 0
<
```
`Docker.DotNet` does not consider the initial …

fix: Do not read from stream with content length of 0

---

src/Docker.DotNet/Models/ContainerPathStatParameters.Generated.cs
tools/specgen/modeldefs.go

Allows extracting Tar balls with original owner. See spec [ContainerPathStatParameters](https://docs.docker.com/engine/api/v1.45/#tag/Container/operation/PutContainerArchive)

Add copyUIDGID to ContainerPathStatParameters

---

src/Docker.DotNet/Daemon/DockerDaemonException.cs
src/Docker.DotNet/MultiplexedStream.cs
test/Docker.DotNet.Tests/MultiplexedStreamTests.cs

In the current version of Docker.DotNet (v3.125.15), there is no support for handling the [Systemerr](https://pkg.go.dev/github.com/docker/docker/pkg/stdcopy#StdType) stream when demultiplexing events from Docker.  
When docker sends `Systemerr`, the library throws an `IOException` with the message "unknown stream type"  
To reproduce this issue, we have a valid container `f13d4aec`
```
root@domain:~# docker logs f13d4aec
{truncated}
2024-06-27 09:27:37.337196+00:00 [info] <0.683.0>  * rabbitmq_management_agent
2024-06-27 09:27:37.337196+00:00 [info] <0.683.0>  * rabbitmq_web_dispatch
2024-06-27 09:27:37.803052+00:00 [info] <0.9.0> Time to start RabbitMQ: 12848 ms
root@domain:~# echo $?
0
```
1. Break json in logs to simulate a scenario where Docker would send a `SystemErr`
```bash
echo …
```

Add support for handling systemerr stream from daemon

---

src/Docker.DotNet/Models/ContainerAttachParameters.Generated.cs
tools/specgen/modeldefs.go

As referred in the api (https://docs.docker.com/engine/api/v1.41/#tag/Container/operation/ContainerAttach)
The data type of the Logs property should be a boolean.

[Container Attach] Wrong data type used for Logs property

---

src/Directory.Build.props

License expression is the preferred way (shows in NuGet.org and used in license validations).

Switch to using PackageLicenseExpression

---

src/Docker.DotNet/Endpoints/IContainerOperations.cs

copyedit comment on IContainerOperations.AttachContainerAsync()
