dotnet/Docker.DotNet

Docker.DotNet/Docker.DotNet.csproj
Docker.DotNet/DockerClient.cs
Docker.DotNet/IDockerClient.cs

Add `IDockerClient` interface as discussed in https://github.com/ahmetalpbalkan/Docker.DotNet/issues/21.

Add IDockerClient interface

---

Docker.DotNet/ContainerOperations.cs
Docker.DotNet/Docker.DotNet.csproj
Docker.DotNet/JsonSerializer.cs
Docker.DotNet/Models/Config.cs
Docker.DotNet/Models/HostConfig.cs
Docker.DotNet/Models/RestartPolicy.cs
Docker.DotNet/Models/SystemInfoResponse.cs
Docker.DotNet/Properties/AssemblyInfo.cs
NuGet/Docker.DotNet.1.1.2.nuspec

Integrating `dev` branch into `master` and deleting `dev`. I did not realize we had two branches and accepted PRs/commits to `dev`. Let's not have two branches unless we're doing something like a big  change that would take a lot time to develop.

Integrate dev into master

---

Docker.DotNet/Properties/AssemblyInfo.cs

Hotfixing AssemblyVersion  change in #19.

Revert AssemblyVersion to 1.0.0.0

---

README.md

Bump version to 1.1.2, update README

---

Docker.DotNet/Models/RestartPolicy.cs

Add undefined restart policy and missing no/unless-stopped.
Fixes #36.

Add no/unless-stopped restart policies

---

Docker.DotNet.BasicAuth/Properties/AssemblyInfo.cs
Docker.DotNet.X509/Properties/AssemblyInfo.cs
Docker.DotNet/Properties/AssemblyInfo.cs

Removing the test internals flags since those projects don't actually exist

Removing the test internals flags since those projects don't actually exist

---

Docker.DotNet.X509/Properties/AssemblyInfo.cs
Docker.DotNet/JsonIso8601AndUnixEpochDateConverter.cs
Docker.DotNet/Properties/AssemblyInfo.cs
Docker.DotNet/QueryStringParameterAttribute.cs

@jterry75 
Cleaning up code to make warnings go away.

Getting rid of unnecessary using statments.

---

Docker.DotNet/BoolQueryStringConverter.cs
Docker.DotNet/EnumerableQueryStringConverter.cs
Docker.DotNet/IQueryStringConverter.cs
Docker.DotNet/JsonQueryStringConverter.cs
Docker.DotNet/MapQueryStringConverter.cs
Docker.DotNet/Models/CommitContainerChangesParameters.Generated.cs
Docker.DotNet/Models/ImageBuildParameters.Generated.cs
Docker.DotNet/Models/ImagesImportParameters.Generated.cs
Docker.DotNet/QueryString.cs
Docker.DotNet/TimeSpanSecondsQueryStringConverter.cs

Resolves: #62 - Correctly serializes list and dictionary in query

---

Docker.DotNet.BasicAuth/project.json
Docker.DotNet/project.json

Fixes the build for .NET Core,uap10 in the netstandard moniker.

---

Docker.DotNet.BasicAuth/project.json
Docker.DotNet/project.json

Reverts ahmetalpbalkan/Docker.DotNet#57

Revert "Fixes the build for .NET Core,uap10 in the netstandard moniker."

---

Docker.DotNet.BasicAuth/BasicAuthCredentials.cs
Docker.DotNet.BasicAuth/MaybeSecureString.cs
Docker.DotNet.BasicAuth/project.json
Docker.DotNet.X509/CertificateCredentials.cs
Docker.DotNet.X509/project.json

This appears to be a standard definition.

Use NETSTANDARD1_3 instead of netstandard1_3

---

Docker.DotNet/Endpoints/NetworkOperations.cs

@jstarks @jterry75 
CreateNetworkAsync was incorrectly using GET instead of POST.

Fixing Network creation.

---

LICENSE
README.md

https://www.youtube.com/watch?v=wVyggTKDcOE
Signed-off-by: Ahmet Alp Balkan

Transfer of Copyrights

---

Docker.DotNet.BasicAuth/BasicAuthCredentials.cs
Docker.DotNet.BasicAuth/MaybeSecureString.cs
Docker.DotNet.BasicAuth/Properties/AssemblyInfo.cs
Docker.DotNet.X509/project.json

Updating netstandard dependencies and cleaning up using statements.

---

Docker.DotNet.BasicAuth/BasicAuthCredentials.cs
Docker.DotNet/AnonymousCredentials.cs
Docker.DotNet/BinaryRequestContent.cs
Docker.DotNet/DockerClient.cs
Docker.DotNet/DockerClientConfiguration.cs
Docker.DotNet/Endpoints/MiscellaneousOperations.cs
Docker.DotNet/HttpUtility.cs
Docker.DotNet/JsonIso8601AndUnixEpochDateConverter.cs
Docker.DotNet/JsonRequestContent.cs
Docker.DotNet/QueryStringConverterInstanceFactory.cs
Docker.DotNet/QueryStringParameterAttribute.cs

* Unused methods removed
* Used nameof (...) instead of "..."
* Default constructors removed. Compiler already generates it by default.
* Pascal case for constant variables
* readonly where possible

code improvements

---

Docker.DotNet.BasicAuth/project.json
Docker.DotNet.X509/project.json
Docker.DotNet/Microsoft.Net.Http.Client/BufferedReadStream.cs
Docker.DotNet/MultiplexedStream.cs
Docker.DotNet/project.json

1. Removes the dependency on System.Buffers for NET 451
2. Removes the dependency on System.Runtime which wasn't around
in .NET 451 days.

WIP: Fixes the nupkg for .NET 451

---

Docker.DotNet/Microsoft.Net.Http.Client/UnixDomainSocketEndPoint.cs

@jterry75 
Makes VSCode happy.

Cleaning up leftover using statement.

---

Docker.DotNet/Endpoints/ContainerOperations.cs
Docker.DotNet/Endpoints/IContainerOperations.cs
README.md

Implemented GetContainerStatsAsync with stream response. 
Readme updated to match Docker.DotNet v2.124.

container stats and readme update

---

Docker.DotNet/Endpoints/ContainerOperations.cs
Docker.DotNet/Endpoints/IContainerOperations.cs

1. Fixes a bug in the ContainerStart operation where we were passing the
wrong value as a config option.

Updates the start options type.

---

Docker.DotNet.X509/RSAUtil.cs
Docker.DotNet.X509/project.json

@jstarks @jterry75 
This adds new constructors for the CertificateCredentials class that will allow for reading from PFX or PEM files.

Adding support for PEM certificates to X509.

---

src/Docker.DotNet/Endpoints/ContainerOperations.cs
src/Docker.DotNet/Endpoints/IContainerOperations.cs
src/Docker.DotNet/Endpoints/IImageOperations.cs
src/Docker.DotNet/Endpoints/IMiscellaneousOperations.cs
src/Docker.DotNet/Endpoints/ImageOperations.cs
src/Docker.DotNet/Endpoints/MiscellaneousOperations.cs
src/Docker.DotNet/Endpoints/StreamUtil.cs
src/Docker.DotNet/Models/ImageOperationProgress.cs

Resolves #108.
Full implements the IProgress<Stream> changes for the v1.13 api change
using JSONMessage JSONProgress and JSONError

Fixes IProgress<stream> for v1.13

---

src/Docker.DotNet/DockerClient.cs
src/Docker.DotNet/Endpoints/ContainerOperations.cs
src/Docker.DotNet/Endpoints/ImageOperations.cs
src/Docker.DotNet/Endpoints/MiscellaneousOperations.cs
src/Docker.DotNet/Endpoints/NetworkOperations.cs
src/Docker.DotNet/Endpoints/SwarmOperations.cs

Replaces the make request method overloads with a proper forwarding chain
that exposes all of the possible overloads for MakeRequest,
MakeRequestForStream, MakeRequestForHijackedResponse
Resolves: #170

Fixes stack overflow recursive call.

---

src/Docker.DotNet/Endpoints/SwarmOperations.cs

Resolves: #180
We shouldnt be passing the parameters object but rather the sub object
that just contains the body data not the body and headers.

Passes the correct sub node to swarm.

---

src/Docker.DotNet/Models/Config.Generated.cs
src/Docker.DotNet/Models/CreateContainerParameters.Generated.cs
src/Docker.DotNet/Models/EmptyStruct.cs
tools/specgen/specgen.go

Resolves: #177
Converts the map[string]struct{} to IDictionary<string,EmptyStruct>

Fixes an issue with docker inspect volumes

---

src/Docker.DotNet/Endpoints/INetworkOperations.cs
src/Docker.DotNet/Endpoints/NetworkOperations.cs
src/Docker.DotNet/Models/NetworksDeleteUnusedParameters.Generated.cs
tools/specgen/modeldefs.go
tools/specgen/specgen.go

Resolves: #160
Implements the /networks/prune API.
Reorders the endpoint to better match the Docker API documentation.

Implements missing functionality for networks.

---

src/Docker.DotNet/Endpoints/SwarmOperations.cs

3891112a69e0ae183808800d7735d6d9337c3a4e broke it

Fix SwarmOperations.CreateServiceAsync

---

src/Docker.DotNet/Endpoints/ISwarmOperations.cs
src/Docker.DotNet/Endpoints/SwarmOperations.cs

Added Nodes operations

---

src/Docker.DotNet/Endpoints/ISwarmOperations.cs
src/Docker.DotNet/Endpoints/SwarmOperations.cs

In my last PR I left an uncommitted change. This PR fix that mistake.

Fix mistake from previous PR

---

src/Docker.DotNet/Endpoints/ImageOperations.cs

fix images/create route to always use POST instead of GET for requests with FromImage

Fix CreateImageAsync HTTP method

---

src/Docker.DotNet/DockerClient.cs
src/Docker.DotNet/Endpoints/IVolumeOperations.cs
src/Docker.DotNet/Endpoints/VolumeOperations.cs
src/Docker.DotNet/Models/VolumesPruneResponse.cs

Implements the Volumes API

---

src/Docker.DotNet/DockerClient.cs
src/Docker.DotNet/Endpoints/ITasksOperations.cs
src/Docker.DotNet/Endpoints/TasksOperations.cs
src/Docker.DotNet/Models/ContainerStatus.Generated.cs
src/Docker.DotNet/Models/IPAMOptions.Generated.cs
src/Docker.DotNet/Models/Network.Generated.cs
src/Docker.DotNet/Models/NetworkAttachment.Generated.cs
src/Docker.DotNet/Models/NetworkSpec.Generated.cs
src/Docker.DotNet/Models/PortStatus.Generated.cs
src/Docker.DotNet/Models/TaskResponse.Generated.cs
src/Docker.DotNet/Models/TaskState.cs
src/Docker.DotNet/Models/TaskStatus.Generated.cs
tools/specgen/specgen.go

Implements the Swarm Task's API

---

src/Docker.DotNet/DockerClient.cs
src/Docker.DotNet/Endpoints/ISecretsOperations.cs
src/Docker.DotNet/Endpoints/SecretsOperations.cs
src/Docker.DotNet/Models/Secret.Generated.cs
src/Docker.DotNet/Models/SecretCreateResponse.Generated.cs
src/Docker.DotNet/Models/SecretSpec.Generated.cs
tools/specgen/modeldefs.go
tools/specgen/specgen.go

Implements the Swarm Secrets API

---

appveyor.yml
src/Docker.DotNet/Endpoints/StreamUtil.cs
src/Docker.DotNet/Endpoints/SystemOperations.cs
test/Docker.DotNet.Tests/Docker.DotNet.Tests.csproj
test/Docker.DotNet.Tests/ISystemOperations.Tests.cs

Adds a null check to the progress for event monitoring.
Adds a cancellation check when an events stream is cancelled.
Partially Resolves #176

Adds SystemOperations tests.

---

src/Docker.DotNet/Endpoints/SwarmOperations.cs

Fixes a bug in UpdateServiceAsync.

---

src/Docker.DotNet/DockerClient.cs
src/Docker.DotNet/IDockerClient.cs

Reorders to match the docs online for Docker.
Adds the missing public elements of the DockerClient.
Resolves: #246

Fixes IDockerClient interface.

---

src/Docker.DotNet/Docker.DotNet.csproj
src/Docker.DotNet/MultiplexedStream.cs

Implements MultiplexedStream ReadToEndAsync

---

README.md

Update readme to include certificate validation examples.

---

src/Docker.DotNet/Models/TaskState.cs

Fixes the valid task states enum.

---

src/Docker.DotNet/DockerClient.cs

DockerClient leaked objects if provided with both a timeout and a custom `CancellationToken`. It no longer does this.
The problem was that the created `CancellationTokenSource` was never disposed of, so it kept being referenced by the parent `CancellationToken` it was linked to. By disposing of the CTS after use the link is broken and the object can be collected.

Do not leak CancellationTokenSources

---

src/Docker.DotNet/Models/ImageBuildParameters.Generated.cs
tools/specgen/modeldefs.go

Adds support for new options in ImageBuildParameters to reflect what docker
has added recently.
Signed-off-by: Justin Terry (VM) <juterry@microsoft.com>

Update ImageBuildParameters to latest set of options

---

test/Docker.DotNet.Tests/Docker.DotNet.Tests.csproj
test/Docker.DotNet.Tests/ISystemOperations.Tests.cs

Hello,
this is a very simple test, that tests if the docker service is running, that explains why the other tests are failing with timeout exceptions.
Thanks,
Steffen

Docker service test

---

src/Docker.DotNet/DockerClient.cs
src/Docker.DotNet/Microsoft.Net.Http.Client/ManagedHandler.cs

Fix for issue #285 
Compatible with .NET 4.5, 4.6, Standard1.6, and Standard 2.0

Fix Issue #285 - Wrong Http Request Version

---

src/Docker.DotNet/Endpoints/PluginOperations.cs

Removes the use of IQueryString from ConfigurePluginAsync()

---

src/Docker.DotNet/Endpoints/ITasksOperations.cs
src/Docker.DotNet/Endpoints/TasksOperations.cs
src/Docker.DotNet/Models/TasksListParameters.Generated.cs
tools/specgen/modeldefs.go
tools/specgen/specgen.go

Resolves: #318 
Signed-off-by: Justin Terry (VM) <juterry@microsoft.com>

Adds filter support to ListTasksAsync

---

src/Docker.DotNet/Endpoints/ContainerOperations.cs
src/Docker.DotNet/Endpoints/IContainerOperations.cs

Add container update

---

appveyor.yml
src/Docker.DotNet.BasicAuth/Docker.DotNet.BasicAuth.csproj
src/Docker.DotNet.X509/Docker.DotNet.X509.csproj
src/Docker.DotNet/Docker.DotNet.csproj

Signed-off-by: Justin Terry (VM) <juterry@microsoft.com>

Publish 3.125.3

---

src/Docker.DotNet/Endpoints/ISystemOperations.cs
src/Docker.DotNet/Endpoints/SystemOperations.cs
src/Docker.DotNet/Models/Actor.Generated.cs
src/Docker.DotNet/Models/Message.Generated.cs
test/Docker.DotNet.Tests/ISystemOperations.Tests.cs
tools/specgen/Godeps/Godeps.json
tools/specgen/specgen.go

Replace jsonmessage.JSONMessage by events.Message for system events stream

---

README.md

I have updated the documentation. I hope this PR will resolve the issue #362

#362 Update readme's stream responses example

---

src/Docker.DotNet/Endpoints/PluginOperations.cs

/plugins/privileges is a GET, not a POST

Fix method /plugins/privileges

---

src/Docker.DotNet/Endpoints/SwarmOperations.cs
src/Docker.DotNet/Models/NodeRemoveParameters.cs

This fixes #508.
As you use generated models, you need to replace my manually created class `NodeRemoveParameters` with your generated one accordingly.

fix(swarm-node-remove): move query parameter to the right place

---

README.md

HostConfig is now passed to the CreateContainerAsync method.

Updated documentation for creating and starting containers

---

src/Docker.DotNet/Endpoints/IVolumeOperations.cs
src/Docker.DotNet/Endpoints/VolumeOperations.cs
test/Docker.DotNet.Tests/IVolumeOperationsTests.cs

Added overload for IVolumeOperations.ListAsync that accepts a VolumesListParameters argument.

IVolumeOperations.ListAsync overload with VolumesListParameters arg

---

src/Directory.Build.props

Fixed Source repository link in nuget package metadata

Fixed 404 in Nuget repository link
